// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBUj_cyGk8ysWc0IcyK1tVBKFE9qx3sGc',
    appId: '1:932451235627:web:d0d9c2ce5944e99f0bb76e',
    messagingSenderId: '932451235627',
    projectId: 'pennywise-fd73a',
    authDomain: 'pennywise-fd73a.firebaseapp.com',
    storageBucket: 'pennywise-fd73a.firebasestorage.app',
    measurementId: 'G-8B7MF1MM1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt_iYFxSwWcnpXOTim12aRpQJXGZZXTQI',
    appId: '1:932451235627:android:81be7cf5a79e935e0bb76e',
    messagingSenderId: '932451235627',
    projectId: 'pennywise-fd73a',
    storageBucket: 'pennywise-fd73a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0A--35NtIw-r1jc2FSaxIK8c-FfYvWiE',
    appId: '1:932451235627:ios:a5b38c54f51e5cd00bb76e',
    messagingSenderId: '932451235627',
    projectId: 'pennywise-fd73a',
    storageBucket: 'pennywise-fd73a.firebasestorage.app',
    iosBundleId: 'com.example.pennywiseWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0A--35NtIw-r1jc2FSaxIK8c-FfYvWiE',
    appId: '1:932451235627:ios:a5b38c54f51e5cd00bb76e',
    messagingSenderId: '932451235627',
    projectId: 'pennywise-fd73a',
    storageBucket: 'pennywise-fd73a.firebasestorage.app',
    iosBundleId: 'com.example.pennywiseWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBUj_cyGk8ysWc0IcyK1tVBKFE9qx3sGc',
    appId: '1:932451235627:web:11c4e5074041d3210bb76e',
    messagingSenderId: '932451235627',
    projectId: 'pennywise-fd73a',
    authDomain: 'pennywise-fd73a.firebaseapp.com',
    storageBucket: 'pennywise-fd73a.firebasestorage.app',
    measurementId: 'G-76QRV0EGJB',
  );
}
